
apt-get update
apt-get upgrade 
apt-get install postgresql-client python-dateutil python-feedparser python-gdata python-ldap python-libxslt1 python-lxml python-mako python-openid python-psycopg2 python-pybabel python-pychart python-pydot python-pyparsing python-reportlab python-simplejson python-tz python-vatnumber python-vobject python-webdav python-werkzeug python-xlwt python-yaml python-zsi wget
wget http://nightly.odoo.com/old/openerp-6.1/6.1.20140804/openerp_6.1-20140804-233536-1_all.deb
dpkg -i openerp_6.1-20140804-233536-1_all.deb
apt-get install install -f